server {
  listen 80;
  server_name localhost;
  root /usr/share/nginx/html;
  index index.html tour.html;

  location / {
    try_files $uri $uri/ /tour.html;
  }

  location ~* \.(js|css|png|jpg|jpeg|gif|svg|xml|swf|wasm)$ {
    expires 7d;
    add_header Cache-Control "public";
    try_files $uri =404;
  }
}
